### ISSUE TITLE
undefined local variable or method `construct_relation_for_association_calculations' for #<ActiveRecord::Relation []>

### ISSUE THREAD

**Issue by glasses618** [khiav223577/pluck_all#38]
**Reproduction steps:**
- Rails 5.2.2.1
- `includes` then `pluck_all`
  ```ruby
  User.where(id: 1).includes(:posts).pluck_all(:id)
  ```

It seems that `construct_relation_for_association_calculations`  was removed in [this commit](https://github.com/rails/rails/commit/bb5b672ac6b4dd694a3f706d98d82f3000ce18cd#diff-1cabaf53664d448a5cbfcf396cd842b1)

**Comment by khiav223577** [comment]
Thanks for reporting it :). 
Would you like to open a PR for this?

**Comment by MasashiYokota** [comment]
@khiav223577 @glasses618 
Hi. I tried to fix this issue. Please review the PR #39 .
Thank you.

**Comment by khiav223577** [comment]
Fixed in 2.0.4. See the [CHANGELOG](https://github.com/khiav223577/pluck_all/blob/master/CHANGELOG.md#v204-20190404).
