### ISSUE TITLE
[Error] delegate method error with mongoid 7.3.3

### ISSUE THREAD

**Issue by liyijie** [khiav223577/pluck_all#56]
/Users/liyijie/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/forwardable.rb:133:in `instance_delegate': wrong number of arguments (given 3, expected 1) (ArgumentError)
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/pluck_all-2.3.2/lib/pluck_all/models/mongoid_extension.rb:14:in `<module:Findable>'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/pluck_all-2.3.2/lib/pluck_all/models/mongoid_extension.rb:13:in `<module:Mongoid>'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/pluck_all-2.3.2/lib/pluck_all/models/mongoid_extension.rb:2:in `<main>'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        from /Users/liyijie/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'

**Comment by khiav223577** [comment]
Look like is was broken since `mongoid` replace `ActiveSupport#delegate` with `Forwardable #delegate` in https://github.com/mongodb/mongoid/pull/4720
