### ISSUE TITLE
Rails 7.0.6 breaks pluck_all

### ISSUE THREAD

**Issue by urmora** [khiav223577/pluck_all#60]
There's a change in activerecord's activerecord/lib/active_record/result.rb private method column_type signature, which now requires three explicit arguments. pluck_all (2.3.3) seems to be directly calling it using .send in lib/pluck_all/models/active_record_extension.rb:63

Fix would be
```
attributes.each_with_index do |(key, attribute), index|
  attributes[key] = result.send(:column_type, key, index, attribute_types).deserialize(attribute)
end
```

**Comment by urmora** [comment]
PS: commit in rails repo introducing this change:
https://github.com/rails/rails/commit/100c86c00eefc69661e9abdfcb6e0a4a2b46676e

**Comment by khiav223577** [comment]
Thanks for the reporting. Just submit a PR and release v2.3.4. 
See the [changelog](https://github.com/khiav223577/pluck_all/blob/master/CHANGELOG.md#v234-20230730) for more details.

Going to close this. Feel fee to reopen this issue if the problem still exists
